version: "3"
services:
  db:
    image: mysql:5.6
    container_name: db_ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - net-backend
    expose:
      - "3306"

  web:
    image: regismrs/ms-products:latest
    container_name: ms_products
    depends_on:
      - db
    networks:
      - net-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_NAME: db_ecommerce
      DATABASE_PORT: 3306

networks:
  net-backend:

volumes:
  db_data: