server:
  port: 8081
spring:
  application:
    name: ms-products
  datasource:
    url: jdbc:mysql://localhost:3306/db_ecommerce?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect