openapi: 3.0.3
info:
  title: Swagger E-Commerce GOC - OpenAPI 3.0
  description: |-
    This is a e-commerce Server based on the OpenAPI 3.0 specification.

    Some useful links:
    - [The Challenge_02-God-of-Codes e-commerce repository](https://github.com/Regismrs/Challenge_02-God-of-Codes)
    - [The base source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8083
tags:
  - name: feedback
    description: Everything about your feedback
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /feedbacks:
    get:
      tags:
        - feedback
      summary: Finds All feedbacks
      description: Return a list of feedbacks
      operationId: getAll
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FeedbackResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStatus500' 
    post:
      tags:
        - feedback
      summary: Add a new feedback to the store
      description: Add a new feedback to the store
      operationId: createFeedback
      requestBody:
        description: Create a new feedback in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedbackRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedbackResponse'          
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStatus400' 
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStatus500' 
  /feedbacks/{id}:
    get:
      tags:
        - feedback
      summary: Find feedback by ID
      description: Returns a single feedback
      operationId: getFeedback
      parameters:
        - name: id
          in: path
          description: ID of feedback to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedbackResponse'          
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStatus400'
        '404':
          description: Feedback not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStatus404'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStatus500'
    put:
      tags:
        - feedback
      summary: Update an existing feedback
      description: Update an existing feedback by Id
      operationId: updateFeedback
      parameters:
        - name: id
          in: path
          description: ID of feedback to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update an existent feedback in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedbackRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedbackResponse'          
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStatus400'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStatus404'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStatus500'
    delete:
      tags:
        - feedback
      summary: Deletes a feedback
      description: delete a feedback, return status No content code 204 is success case.
      operationId: deleteFeedback
      parameters:
        - name: id
          in: path
          description: Feedback id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStatus404'
  
components:
  schemas:
    FeedbackRequest:
      required:
        - order_id
        - scale
        - comment
      properties:
        order_id:
          type: integer
          format: int64
          example: 1
        scale:
          $ref: '#/components/schemas/ScaleEnum'
        comment:
          type: string
          example: "gostei"
    FeedbackResponse:
      required:
        - id
        - order_id
        - scale
        - comment
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        order_id:
          type: integer
          format: int64
          example: 1
        scale:
          $ref: '#/components/schemas/ScaleEnum'
        comment:
          type: string
          example: "gostei"
    ResponseStatus400:
      type: object
      properties:
        code:
          type: integer
          format: int64
          example: 400
        status:
          type: string
          example: Bad request
        message:
          type: string
          example: ...
        details:
          type: array
          items:
            $ref: '#/components/schemas/ResponseDetailsItem'
    ScaleEnum:
      type: string
      enum:
        - SATISFIED
        - VERY_SATISFIED
        - NEUTRAL
        - DISSATISFIED
        - VERY_DISSATISFIED
    ResponseStatus404:
      type: object
      properties:
        code:
          type: integer
          format: int64
          example: 404
        status:
          type: string
          example: Not Found
        message:
          type: string
          example: ...
        details:
          type: array
          items:
            $ref: '#/components/schemas/ResponseDetailsItem'
          example: []
    ResponseStatus500:
      type: object
      properties:
        code:
          type: integer
          format: int64
          example: 500
        status:
          type: string
          example: Internal server error
        message:
          type: string
          example: ...
        details:
          type: array
          items:
            $ref: '#/components/schemas/ResponseDetailsItem'
          example: []
    ResponseDetailsItem:
      type: object
      properties:
        field:
          type: string
          example: "fieldName"
        message:
          type: string
          example: "fieldName can't ..."