CREATE DATABASE IF NOT EXISTS db_ecommerce;

USE db_ecommerce;
CREATE TABLE feedback_tb(
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  scale ENUM('VERY_DISSATISFIED', 'DISSATISFIED', 'NEUTRAL', 'SATISFIED', 'VERY_SATISFIED') NOT NULL,
  `comment` VARCHAR(255));